#!/bin/bash

# File to check (relative to repo root)
FILENAME="ip_country/src/dbip_country.rs"

if ! git diff --cached --name-only | grep -q "^$FILENAME$"; then
  exit 0
fi

# find 'Nonexistents' country in dbip_
NOEX = $(< "$FILENAME" | grep '("NOEX", "Nonexistents")')
NONEXISTENT = $?

# Get local file size (staged version, not working copy)
LOCAL_SIZE=$(git ls-files --stage | grep "$FILENAME" | awk '{print $2}' | xargs git cat-file -s)

if [ LOCAL_SIZE > 1000 || NONEXISTENT ]; then
  echo "❌ Commit blocked: $FILENAME size it not dev version, we want to keep dev version under 1 MB."
  echo "   Local file size:  $LOCAL_SIZE bytes"
  echo "   File must contain '(\"NOEX\", \"Nonexistents\")' country, and insted contains: '$NOEX'"
  echo "   Please sync the file with the remote before committing using:"
  echo "   git checkout HEAD -- ip_country/src/dbip_country.rs"
  exit 1
fi

# All good
exit 0
