# Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved.
FROM trufflesuite/ganache-cli:v6.7.0

ADD ./entrypoint.sh /app/

EXPOSE 18545

ENTRYPOINT /app/entrypoint.sh
